/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-application-conventions")
}

dependencies {
    implementation("org.apache.commons:commons-text") //llibreria que té moltes utilitats
    implementation("com.mysql:mysql-connector-j:9.3.0")
    implementation(project(":model"))
    implementation(project(":repository"))
    implementation("com.github.freva:ascii-table:1.8.0")
}

application {
    // Define the main class for the application.
    mainClass = "org.example.app.App"
}
