/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-application-conventions")
}

dependencies {
    implementation(project(":model"))
    implementation(project(":repositories"))
    implementation(project(":jdbc"))
    implementation(project(":jpa"))
    

    implementation("org.apache.commons:commons-text") //llibreria que té moltes utilitats
    implementation("com.mysql:mysql-connector-j:9.3.0")
    implementation("com.github.freva:ascii-table:1.8.0")
}

application {
    // Define the main class for the application.
    mainClass = "cat.uvic.teknos.registry.app.App"
}
